services:
  db:
    image: "postgres:17"
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: "LibraryDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "LibraryDb"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library_network

  webapi:
    build:
      context: .
      dockerfile: LibraryApi/Dockerfile
    container_name: library_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=LibraryDb;Username=postgres;Password=1234
    ports:
      - "8080:8080"
    volumes:
      - ./LibraryApi/appsettings.Docker.json:/app/appsettings.json
    networks:
      - library_network

  libraryapi.tests:
    build:
      context: .
      dockerfile: LibraryApi.Tests/Dockerfile
    depends_on:
      webapi:
        condition: service_started
    networks:
      - library_network

networks:
  library_network:

volumes:
  postgres_data:
